### ISSUE TITLE
Display nothing on Closed Trades,Trades Summary,Daily Profit, Graph

### ISSUE THREAD

**Issue by kulipanggul-ops** [froggleston/freqtrade-frogtrade9000#12] opened 2022-03-05 10:23 UTC
Got error
ERROR: unsupported operand type(s) for /: 'str' and 'int' 

Python v3.9
![Screen Shot 1](https://user-images.githubusercontent.com/70523739/156879150-d4d1ca9a-955a-4832-8873-9251b38c96f1.png)

**Comment by froggleston** [comment] 2022-03-07 11:02
This is usually because you have no trades. I thought I fixed this but I'll double check the code.

**Comment by froggleston** [comment] 2022-08-30 17:47
This should now be fixed in the latest commit

**Comment by froggleston** [comment] 2022-09-11 14:31
I can't reproduce this with new bots, so closing.

**Closed by froggleston** 2022-09-11 14:31 UTC
